name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  builder: "paketobuildpacks/builder-jammy-base"
  pack_version: "0.33.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pack
        run: |
          wget -q https://github.com/buildpacks/pack/releases/download/v${{ env.pack_version }}/pack-v${{ env.pack_version }}-linux.tgz -O - | tar -xz
          chmod +x ./pack

      - name: Build and push Docker image
        run: |
          ./pack build --no-color --builder ${{ env.builder }} \
            --path src/my-app
